autosort: True
# If true, separate flow control names from their parentheses with a space
separate_ctrl_name_with_space: True

# If true, separate function names from parentheses with a space
separate_fn_name_with_space: False

# If a statement is wrapped to more than one line, than dangle the closing
# parenthesis on its own line.
dangle_parens: True

#max_subgroups_hwrap: 1